<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CP5200">
      <HintPath>..\docs\Rotuloselectronicos.NET_API+ejemplos\Rotuloselectronicos.NET API\Rotuloselectronicos.NET API SDK\CP5200.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\docs\Rotuloselectronicos.NET_API+ejemplos\Rotuloselectronicos.NET API\Rotuloselectronicos.NET API SDK\CP5200.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project> 